-- 0006 — committee run history.
--
-- A run is an immutable audit record: what the system saw, who it asked, and what came back.
-- The bulky parts are JSONB rather than normalized tables on purpose. Normalizing the report
-- would add roughly eight write-once, read-whole tables, and every future change to
-- CommitteeReport would force historical rows into a shape that does not describe what actually
-- happened at the time. JSONB keeps each row faithful to the schema version that produced it.
--
-- The exception is aggregate usage: cost and token counts are promoted to real columns because
-- they get queried and summed across runs.
--
-- No credential appears in any column here. Every write goes through
-- app.core.credentials.scrub_for_storage() first.

create table public.committee_runs (
  id        uuid primary key default gen_random_uuid(),
  -- run_<uuid4hex[:16]>, generated by RunContext. Correlates rows with application logs.
  run_id    text not null unique,
  user_id   uuid not null references public.app_users(id) on delete cascade,
  -- The originating profile/portfolio may later be edited or deleted; the snapshots below are
  -- what the run actually saw, so history survives either way.
  profile_id    uuid references public.financial_profiles(id) on delete set null,
  portfolio_id  uuid references public.portfolios(id) on delete set null,

  question  text not null,
  depth     text not null check (depth in ('quick', 'balanced', 'deep')),
  model     text not null,
  status    text not null default 'succeeded' check (status in ('succeeded', 'failed')),
  -- Populated on failure. Already sanitized by safe_error_message().
  error_message text,

  -- Immutable snapshots.
  profile_snapshot     jsonb not null,
  portfolio_snapshot   jsonb,
  analytics            jsonb not null,
  portfolio_analytics  jsonb,
  guardrails           jsonb not null default '[]',
  selection            jsonb not null,
  -- Null when the run failed before synthesis. The user was still billed for what ran, which
  -- is why the usage columns below are populated regardless of status.
  report               jsonb,

  total_calls                  integer not null default 0,
  failed_calls                 integer not null default 0,
  total_input_tokens           integer not null default 0,
  total_output_tokens          integer not null default 0,
  total_cache_read_tokens      integer not null default 0,
  total_cache_creation_tokens  integer not null default 0,
  total_latency_ms             double precision not null default 0,
  -- Null means "could not be priced", never zero — an unknown cost is not a free one.
  estimated_cost_usd           numeric(12,6),
  pricing_version              text not null,
  unpriced_models              text[] not null default '{}',

  created_at  timestamptz not null default now()
);

comment on column public.committee_runs.estimated_cost_usd is
  'Null means the model was not in the pricing table. Unknown cost, not free.';

create index committee_runs_user_idx on public.committee_runs (user_id, created_at desc);
create index committee_runs_profile_idx on public.committee_runs (profile_id);

-- Per-stage and per-advisor cost breakdown. Normalized rather than JSONB because the
-- interesting queries are cross-run: "what does cross-examination actually cost me on average".
create table public.run_cost_lines (
  id      uuid primary key default gen_random_uuid(),
  run_id  text not null references public.committee_runs(run_id) on delete cascade,
  kind    text not null check (kind in ('stage', 'advisor')),
  label   text not null,
  calls          integer not null default 0,
  input_tokens   integer not null default 0,
  output_tokens  integer not null default 0,
  estimated_cost_usd numeric(12,6),

  constraint run_cost_lines_unique unique (run_id, kind, label)
);

create index run_cost_lines_run_idx on public.run_cost_lines (run_id, kind);

-- One row per LLM call. Kept for latency work and for explaining a surprising bill.
create table public.run_llm_calls (
  id       uuid primary key default gen_random_uuid(),
  run_id   text not null references public.committee_runs(run_id) on delete cascade,
  call_id  text not null,
  -- Pipeline stage: independent, cross_examination, risk_challenge, synthesis, ...
  role     text not null,
  advisor_id  text,
  model       text not null,
  input_tokens           integer not null default 0,
  output_tokens          integer not null default 0,
  cache_read_tokens      integer not null default 0,
  cache_creation_tokens  integer not null default 0,
  latency_ms  double precision not null default 0,
  started_at  timestamptz not null,
  -- Sanitized provider error, or null when the call succeeded.
  error       text,

  constraint run_llm_calls_unique unique (run_id, call_id)
);

create index run_llm_calls_run_idx on public.run_llm_calls (run_id);
